import express from "express";
import fs from "fs/promises";
import path from "path";

function plmnFromImsi(imsi = "") {
  const digits = imsi.replace(/\D/g, "");
  const mcc = digits.slice(0, 3) || "001";
  const mnc = digits.slice(3, 5) || "01";
  return { mcc, mnc };
}

function buildUeConfig(doc, gnbName) {
  // 구성 정보는 UERANSIM 기본 템플릿을 따르며 MongoDB 필드가 없으면 안전한 기본값 사용
  const { mcc, mnc } = plmnFromImsi(doc.imsi);
  const key = doc.security?.k || "";
  const opc = doc.security?.opc || doc.security?.op || "";
  const supi = doc.imsi.startsWith("imsi-") ? doc.imsi : `imsi-${doc.imsi}`;

  return `# Auto-generated by ran-ui
supi: "${supi}"
mcc: "${mcc}"
mnc: "${mnc}"
protectionScheme: 0
routingIndicator: "0000"
key: "${key}"
op: "${opc}"
opType: "OPC"
amf: "${doc.security?.amf || "8000"}"
imei: "${doc.imei || "356938035643803"}"
imeiSv: "${doc.imeiSv || "4370816125816151"}"
tunNetmask: "255.255.255.0"
gnbSearchList:
  - "${gnbName}"
uacAic:
  mps: false
  mcs: false
uacAcc:
  normalClass: 0
  class11: false
  class12: false
  class13: false
  class14: false
  class15: false
sessions:
  - type: "IPv4"
    apn: "${doc.slice?.[0]?.session?.[0]?.name || "internet"}"
    slice:
      sst: ${doc.slice?.[0]?.sst || 1}
      sd: ${doc.slice?.[0]?.sd || 1}
configured-nssai:
  - sst: ${doc.slice?.[0]?.sst || 1}
    sd: ${doc.slice?.[0]?.sd || 1}
default-nssai:
  - sst: ${doc.slice?.[0]?.sst || 1}
    sd: ${doc.slice?.[0]?.sd || 1}
integrity:
  IA1: true
  IA2: true
  IA3: true
ciphering:
  EA1: true
  EA2: true
  EA3: true
integrityMaxRate:
  uplink: "full"
  downlink: "full"
`;
}

async function writeUeConfig(doc, gnbName, mountDir) {
  // 컨테이너에서 읽을 수 있는 경로(`mountDir`) 아래에 자동 생성된 YAML을 저장
  const fileName = `${doc.imsi}.yaml`;
  const containerPath = path.join(mountDir, "generated", fileName);
  await fs.mkdir(path.dirname(containerPath), { recursive: true });
  await fs.writeFile(containerPath, buildUeConfig(doc, gnbName), "utf8");
  return { fileName, containerPath };
}

async function listManagedContainers(docker) {
  // ran-ui 레이블로 태깅된 컨테이너만 조회해 IMSI↔컨테이너 상태를 빠르게 확인
  const summaries = await docker.listContainers({
    all: true,
    filters: { label: ["ran-ui=ue"] },
  });
  const map = new Map();
  for (const summary of summaries) {
    const imsi = summary.Labels?.["ran-ui.imsi"];
    if (imsi) {
      map.set(imsi, summary);
    }
  }
  return map;
}

export default function createUeRouter(
  subscriberCollection,
  { docker, config, network, image }
) {
  if (!docker) {
    throw new Error("docker client missing");
  }

  const router = express.Router();

  router.get("/", async (_req, res, next) => {
    try {
      const docs = await subscriberCollection.find().toArray();
      const containerMap = await listManagedContainers(docker);
      const items = docs.map((doc) => {
        const container = containerMap.get(doc.imsi);
        return {
          id: doc.imsi,
          supi: doc.imsi,
          hasContainer: Boolean(container),
          containerStatus: container?.State || "missing",
          containerId: container?.Id?.slice(0, 12) || null,
          slice: doc.slice,
          gnbName: doc.gnbName || "RAN-GNB",
        };
      });
      res.json({ items });
    } catch (err) {
      next(err);
    }
  });

  router.post("/", async (req, res, next) => {
    try {
      const { imsi, key, opc, gnbName } = req.body || {};
      if (!imsi || !key || !opc || !gnbName) {
        return res
          .status(400)
          .json({ error: "imsi, key, opc, gnbName are required" });
      }

      const payload = {
        imsi,
        security: {
          k: key,
          opc,
        },
        gnbName,
        status: "pending",
        createdAt: new Date(),
      };

      await subscriberCollection.insertOne(payload);
      return res
        .status(201)
        .json({ message: "UE stored in MongoDB", id: imsi });
    } catch (err) {
      next(err);
    }
  });

  router.post("/:id/spawn", async (req, res, next) => {
    try {
      const imsi = req.params.id;
      const doc = await subscriberCollection.findOne({ imsi });
      if (!doc) {
        return res.status(404).json({ error: "UE not found in database" });
      }

      const containerName = `ran-ue-${imsi}`;
      try {
        const existing = docker.getContainer(containerName);
        await existing.inspect();
        return res
          .status(409)
          .json({ error: "UE container already exists", containerName });
      } catch (err) {
        if (err.statusCode && err.statusCode !== 404) {
          throw err;
        }
      }

      if (!doc.security?.k || !(doc.security?.opc || doc.security?.op)) {
        return res
          .status(400)
          .json({ error: "UE security credentials missing in MongoDB" });
      }

      if (!config?.hostDir || !config?.mountDir) {
        return res
          .status(500)
          .json({ error: "Configuration directories not defined" });
      }

      const { fileName, containerPath } = await writeUeConfig(
        doc,
        doc.gnbName || "RAN-GNB",
        config.mountDir
      );
      const hostPath = path.join(config.hostDir, "generated", fileName);

      const binds = [`${hostPath}:/config/${fileName}:ro`];
      const createOptions = {
        name: containerName,
        Image: image,
        Cmd: ["nr-ue", "-c", `/config/${fileName}`],
        Labels: {
          "ran-ui": "ue",
          "ran-ui.imsi": imsi,
        },
        HostConfig: {
          Binds: binds,
          Privileged: true,
        },
        NetworkingConfig: {
          EndpointsConfig: {
            [network]: {},
          },
        },
      };

      const container = await docker.createContainer(createOptions);
      await container.start();

      await subscriberCollection.updateOne(
        { imsi },
        {
          $set: {
            status: "running",
            containerId: container.id,
            configPath: containerPath,
          },
        }
      );

      res.status(201).json({
        message: "UE container started",
        containerId: container.id,
        containerName,
      });
    } catch (err) {
      next(err);
    }
  });

  router.delete("/:id", async (req, res, next) => {
    try {
      const result = await subscriberCollection.deleteOne({ imsi: req.params.id });
      if (!result.deletedCount) {
        return res.status(404).json({ error: "UE not found" });
      }
      return res.json({ message: "UE removed", id: req.params.id });
    } catch (err) {
      next(err);
    }
  });

  return router;
} 
