FROM node:20-bullseye

# install git
RUN apt update && apt install -y git && apt clean

# clone open5gs repo
RUN git clone https://github.com/open5gs/open5gs.git /open5gs

# build webui
WORKDIR /open5gs/webui

RUN npm ci
RUN npm run build

ENV HOSTNAME=0.0.0.0
ENV PORT=3000
ENV DB_URI=mongodb://o5gs-mongo/open5gs

EXPOSE 3000

CMD ["npm", "run", "dev"]
